config/routes.rb
Rails.application.routes.draw do
  root "airlines#index"

  get 'auth/:provider/callback' => 'sessions#create' 

  # users routes
  #admin user
  get '/account' => 'users#index'
  # regular users
  get '/login', to: 'users#login'
  post '/login', to: 'users#loggedin'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/logout', to: 'users#destroy'

  # tickets routes 
  get '/tickets/cheapest', to: 'tickets#cheapest', as: 'cheapest'
  get '/tickets/expensive', to: 'tickets#expensive', as: 'expensive'
  get '/tickets/:id/buy', to: 'tickets#edit', as: 'buy_ticket'
  get '/expensive_tickets', to: 'tickets#expensive_tickets', as: 'expensive_tickets'
  #flights 
  get '/airlines/:airline_id/flights/cheapest', to: 'flights#cheapest', as: 'cheapest_flight'
  get '/airlines/:airline_id/flights/expensive', to: 'flights#expensive', as: 'expensive_flight'

  resources :airlines, only: [:index, :show] do 
   resources :flights, only: [:index, :show]
end
resources :flights, only: [:show] do 
  resources :tickets, only: [:index, :new, :create, :show]
end

resources :flights, only: [:index, :show] 
resources :tickets, only: [:index, :show, :new, :create, :update, :destroy]

resources :passengers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ActiveRecord::Base
    has_many :tickets
    has_many :passengers, through: :tickets
    belongs_to :airline
    validates :departure, :arrival, :title, presence: true
    scope :cheapest, -> { order(price: :asc) }
    scope :expensive, -> { order(price: :desc) }
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    before_action :redirect_if_not_login
    def index
        # shows a list of different flights
        if !params[:airline_id].nil?
         @flights = Airline.find_by_id(params[:airline_id]).flights
        else
            @flights = Flight.all
        end
    end 

    def show
        #  shows the times of flight
        @flight = Flight.find_by_id(params[:id])
        if !@flight.nil?
            @tickets = @flight.tickets
        elsif !params[:airline_id].nil? 
            redirect_to root_path
        end
    end 

    def expensive 
        @flight = Flight.find_by_id(params[:airline_id])
        @flight.tickets = Ticket.expensive.limit(3)
        render :show
    end 

    def cheapest
        @flight = Flight.find_by_id(params[:airline_id])
        @flight.tickets = Ticket.cheapest.limit(3)
        render :show
    end
    
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/index.erb
<% @flights.each do |flight| %>
    <h1><%= flight.title %> - <%= flight.departure %> - <%= flight.arrival %></h1> <br>

    <div>
    <table>
        <th>Ticket Number</th> <th>Price</th> <th>Seat</th> <th>Purchased</th>
        <% flight.tickets.each do |ticket| %>
        <tr>
            <td><%= ticket.ticket_num %></td>
            <td> <%= ticket.price %></td>
            <td><%= ticket.seat_num %></td>
            <td>  
                <% if ticket.passenger.nil? %>
                    <%= link_to 'Buy Ticket', buy_ticket_path(ticket) %>
                <% else %>
                   <div>Purchased</div> 
                <% end %>
            </td>
        </tr>
        <% end %>
    </table>

    <div id="filters">
     <%= link_to 'Create ticket', new_flight_ticket_path(flight) %>
        <% if !flight.tickets[1].nil? %>
            <%= link_to 'Cheapest ticket', cheapest_flight_path(flight) %>
            <%= link_to 'Expensive ticket', expensive_flight_path(flight) %>
        <% end %>
    </div>
</div> <br><br>
<% end %>

app/views/flights/show.erb
<h1> <%= @flight.airline.name %> <%= @flight.title %></h1> <br>
<h3>  <%= pluralize(@flight.passengers.size, 'passenger') %> booked</h3> <br>
<div>
    Departure: <%= @flight.departure %> <br>
    Arrival: <%= @flight.arrival %> <br>
    Destination: <%= @flight.airline.destination %>
</div> <br>
<div>
    <table>
        <th>Ticket Number</th> <th>Price</th> <th>Seat</th> <th>Purchased</th>
            <% if !@flight.tickets[1].nil? %>
                    <% @flight.tickets.each do |ticket| %>
                        <tr>
                            <td><%= ticket.ticket_num %></td>
                            <td> $<%= ticket.price %></td>
                            <td><%= ticket.seat_num %></td>
                            <td>  
                                <% if ticket.passenger.nil? %>
                                    <%= link_to 'Buy Ticket', buy_ticket_path(ticket) %>
                                <% else %>
                                    <div>Purchased</div>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
            <% else %>
                <tr>
                    <td><%= @tickets.ticket_num %></td>
                    <td> $<%= @tickets.price %></td>
                    <td><%= @tickets.seat_num %></td>
                    <td>  
                        <% if @tickets.passenger.nil? %>
                            <%= link_to 'Buy Ticket', buy_ticket_path(@tickets) %>
                        <% else %>
                           <span>purchased</span> 
                        <% end %>
                    </td>
                </tr>
            <% end %>
    </table>
        <div id="filters">
            <%= link_to 'Create Ticket', new_flight_ticket_path(@flight) %> 
                <%= link_to 'Show All Tickets', flights_path %>
            <% if !@flight.tickets[1].nil? %>
                <%= link_to 'Cheapest Ticket', cheapest_flight_path(@flight.tickets) %> 
                <%= link_to 'Expensive Ticket', expensive_flight_path(@flight.tickets) %> 
            <% else %>
                <%= link_to "Show Flight's Tickets", flight_path(@flight) %>
            <% end %>
        </div>
</div>