config/routes.rb
Rails.application.routes.draw do
  root "airlines#index"

  get 'auth/:provider/callback' => 'sessions#create' 

  # users routes
  #admin user
  get '/account' => 'users#index'
  # regular users
  get '/login', to: 'users#login'
  post '/login', to: 'users#loggedin'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/logout', to: 'users#destroy'

  # tickets routes 
  get '/tickets/cheapest', to: 'tickets#cheapest', as: 'cheapest'
  get '/tickets/expensive', to: 'tickets#expensive', as: 'expensive'
  get '/tickets/:id/buy', to: 'tickets#edit', as: 'buy_ticket'
  get '/expensive_tickets', to: 'tickets#expensive_tickets', as: 'expensive_tickets'
  #flights 
  get '/airlines/:airline_id/flights/cheapest', to: 'flights#cheapest', as: 'cheapest_flight'
  get '/airlines/:airline_id/flights/expensive', to: 'flights#expensive', as: 'expensive_flight'

  resources :airlines, only: [:index, :show] do 
   resources :flights, only: [:index, :show]
end
resources :flights, only: [:show] do 
  resources :tickets, only: [:index, :new, :create, :show]
end

resources :flights, only: [:index, :show] 
resources :tickets, only: [:index, :show, :new, :create, :update, :destroy]

resources :passengers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
    belongs_to :flight
    belongs_to :passenger, optional: true
    scope :cheapest, -> { order(price: :asc) }
    scope :expensive, -> { order(price: :desc) }
    scope :expensive_tickets, -> { where('price > 1000') }
    validates :seat_num, :ticket_num, presence: true
    validates :price, numericality: { :greater_than_or_equal_to => 0 }
end 

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    before_action :redirect_if_not_login
    before_action :sets_params, only: [:show, :edit, :destroy, :update]

    def index 
        if !params[:flight_id].nil?
            #find the flight
            #get the tickets aso
            @tickets = Flight.find_by_id(params[:flight_id]).tickets
        else 
             @tickets = Ticket.all
        end
    end 

    def show 
        redirect_if_wrong_id(@ticket, tickets_path)
    end 

    def expensive 
        @ticket = Ticket.expensive.first
        render :show
    end 

    def cheapest
        @ticket = Ticket.cheapest.first
        render :show
    end

    def expensive_tickets
        @tickets = Ticket.expensive_tickets
        render :index
    end

    def new 
        # buy a ticket with that has a specific time 
        @ticket = Ticket.new(flight_id: params[:flight_id])
    end 

    def create 
        @ticket = Ticket.new(params_pair)
        if @ticket.save
            redirect_to ticket_path(@ticket)
        else 
            render :new
        end
    end 

    def edit 
        redirect_if_wrong_id(@ticket, tickets_path)
    end 

    def update 
        @message = ""
        @ticket.update(passenger_id: params[:ticket][:passenger_id])         
        if @ticket.passenger.nil? 
            @message = "Please Choose a Passenger."
           render :edit
        elsif current_user.id != @ticket.passenger.user_id 
            redirect_to root_path
        else 
            redirect_to ticket_path(@ticket)
        end
    end

    def destroy
        # remove ticket or cancel it
        @ticket.passenger_id = nil
        @ticket.save
        redirect_to ticket_path(@ticket)
        # this part is only for admin
        # @ticket.delete_all
    end

    private 

    def sets_params
        @ticket = Ticket.find_by_id(params[:id])
    end 

    def params_pair
        params.require(:ticket).permit(:ticket_num, :seat_num, :price, :flight_id)
    end 

    # def ticket_order(.ordered)
    #     @tickets = Ticket.order(price: ordered).first
    #     render :index
    # end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_errors.erb
<% if @ticket.errors.any? %>
    <div id="error_explanation">
        <h2>
        <%= pluralize(@ticket.errors.count, "error") %>
        prohibited this Ticket from being saved:
        </h2>
        <ul>
        <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %> 

app/views/tickets/edit.html.erb
<h1>Ticket: <%= @ticket.ticket_num %></h1>
<div id="login_form">
    <%= form_for @ticket do |f| %>
        <%=f.label "Passenger"  %> <br>
        <%=f.collection_select(:passenger_id, current_user.passengers, :id, :full_name, {prompt: "Please select passenger"}) %> <br>
        <%= f.submit "Buy Ticket" %>
        <%= render 'errors' %>
    <% end %>

    <% if @ticket.passenger.nil? %>

    <% elsif current_user.id !=  @ticket.passenger.user_id  %>
        <h3> What are you doing?</h3>
    <% else %>
        <%= form_for @ticket, method: :delete do |f| %>
        <%= f.submit 'cancel Passenger'%>
        <% end %>
    <% end %>
</div>
<% if current_user.passengers.empty? %>
    <div id="error_explanation"> You have no Passengers to select</div>
<% end %>
    <div id="error_explanation"> <%= @message %> </div>

app/views/tickets/index.html.erb
<% if !@tickets.empty? %>
<ul>
        <% @tickets.each do |ticket| %>
            <% if ticket.flight.nil? %>
            <h2> Ticket <%= ticket.ticket_num %> has no Flight</h2>
            <% else %>
            <h3>Plane: <%= ticket.flight.title %></h3>
            <% end %>
            <li>
                Ticket Number: <%= ticket.ticket_num %> -
                Seat Number: <%= ticket.seat_num %> -
                Price: $<%= ticket.price %>
            </li>
        <% end %>
    <%= link_to 'Cheapest Ticket', cheapest_path %>
    <%= link_to 'Expensive Ticket', expensive_path %>
    <%= link_to 'Create Ticket', new_ticket_path %>
</ul>
    <% else %>
    <h2>Tickets are sold Out!!</h2>
    <% end %>

app/views/tickets/new.html.erb
<%# This is only for Admin %>
<div id="login_form">
<% if !@ticket.flight.nil? %>
    <h1> New Ticket for: <%= @ticket.flight.title %> </h1> <br>
<% else %>
     <h1> New Ticket </h1> <br>
<% end %>
<%= form_for @ticket do |f| %>
    <%= f.text_field :ticket_num, placeholder: 'Ticket Number'%> <br>
    <%# Some seat will be taken %>
    <%= f.number_field :seat_num , placeholder: 'Seat Number'%><br> <br>
        <% if @ticket.flight.nil? %>
            <%= f.collection_select(:flight_id, Flight.all, :id, :title, {prompt: "Choose Flight"}) %> <br>
        <% else %>
           <%= f.hidden_field :flight_id %> 
        <% end %>
    <%= f.number_field :price, value: 0, step: :any, placeholder: 'Price'%> <br>
    <%= f.submit %>
         <%= render 'errors' %>
<% end %>
</div>

app/views/tickets/show.html.erb
     <% if @ticket.flight.nil?  %>
          <h2> Ticket <%= @ticket.ticket_num %> has no Flight</h2>
     <% else %>
        <h1> Plane: <%= @ticket.flight.title %></h1>
        <div>Plane Departing: <%= @ticket.flight.departure %></div>
        <div>Plane Arriving: <%= @ticket.flight.arrival %></div> <br><br>
        <h3>Ticket Number: <%= @ticket.ticket_num %></h3>
     <% end %>

<h2>Seat Number: <%= @ticket.seat_num %></h2>

<h3>Price: $<%= @ticket.price %></h2> <br><br>
<% if @ticket.passenger.nil? %>
    <%= link_to "Purchase Ticket", buy_ticket_path(@ticket) %>
<% elsif current_user.id == @ticket.passenger_id%>
    <h3><%= @ticket.passenger.full_name %> owns this ticket.</h3>
    <div id="login_form">
     <%= form_for @ticket, method: :delete do |f| %>
        <%= f.submit 'cancel Passenger'%>
    <% end %>
    </div>
<% end %>
<div id="filters">

<% if !@ticket.flight_id.nil? %>
    <%= link_to 'Show all tickets', flight_path(@ticket.flight_id) %>
<% else %>
    <%= link_to 'Show all tickets', tickets_path %>
<% end %>
</div>