config/routes.rb
Rails.application.routes.draw do
  root "airlines#index"

  get 'auth/:provider/callback' => 'sessions#create' 

  # users routes
  #admin user
  get '/account' => 'users#index'
  # regular users
  get '/login', to: 'users#login'
  post '/login', to: 'users#loggedin'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/logout', to: 'users#destroy'

  # tickets routes 
  get '/tickets/cheapest', to: 'tickets#cheapest', as: 'cheapest'
  get '/tickets/expensive', to: 'tickets#expensive', as: 'expensive'
  get '/tickets/:id/buy', to: 'tickets#edit', as: 'buy_ticket'
  get '/expensive_tickets', to: 'tickets#expensive_tickets', as: 'expensive_tickets'
  #flights 
  get '/airlines/:airline_id/flights/cheapest', to: 'flights#cheapest', as: 'cheapest_flight'
  get '/airlines/:airline_id/flights/expensive', to: 'flights#expensive', as: 'expensive_flight'

  resources :airlines, only: [:index, :show] do 
   resources :flights, only: [:index, :show]
end
resources :flights, only: [:show] do 
  resources :tickets, only: [:index, :new, :create, :show]
end

resources :flights, only: [:index, :show] 
resources :tickets, only: [:index, :show, :new, :create, :update, :destroy]

resources :passengers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/airline.rb
class Airline < ActiveRecord::Base 
    has_many :flights
    has_many :passengers, through: :flights
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController
    before_action :redirect_if_not_login
    def index 
        @airlines = Airline.all
    end 

    def show 
        @airline = Airline.find_by_id(params[:id])
        redirect_if_wrong_id(@airline, root_path)
    end
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/views/airlines/index.html.erb
<ul>
<h1> Airlines</h1> <br><br>
<% @airlines.each do |airline| %>
   <h3><%= airline.name %></h3>
   <li><%= airline.address %> - <%= airline.destination %> <%=link_to 'View Airline', airline_path(airline) %></li>
        <div>This has <%= pluralize(airline.flights.count, 'flight') %></div> <br><br>
<% end %>
</ul>

app/views/airlines/show.html.erb
<h1><%= @airline.name %></h1>

<h3><%= @airline.address %></h3>

<ul>
<% @airline.flights.each do |flight| %>
  <li>
  <h2><%= flight.title %> - Departure: <%= flight.departure %> - Arrival: <%= flight.arrival %> </h2> <br>
    <h3>  <%= pluralize(flight.passengers.size, 'passenger') %> booked</h3> <br><br>
    <h3> Your destination: <%= @airline.destination %></h3> <br>
          
    <% if !flight.tickets.empty? %>
        <%= link_to 'View Flight', airline_flight_path(@airline, flight.id) %><br> <br>
      <h1> Tickets </h1>  
        <table border="1" > 
            <th> Ticket Number </th> <th>Seat Number</th> <th>Price</th>
          <% flight.tickets.each  do |ticket| %>
            <tr align="center">
              <td><%= link_to ticket.ticket_num, ticket_path(ticket) %> </td>
              <td><%= ticket.seat_num %></td>
              <td>$<%= ticket.price %></td>
            </tr>
          <% end %>
        </table> <br><br>
        <% else %>
        <h3 stlye="color: red;"> Tickets are sold out!!!</h3>
    <% end %>
  </li>
<% end %>
</ul>