config/routes.rb
Rails.application.routes.draw do
  root "airlines#index"

  get 'auth/:provider/callback' => 'sessions#create' 

  # users routes
  #admin user
  get '/account' => 'users#index'
  # regular users
  get '/login', to: 'users#login'
  post '/login', to: 'users#loggedin'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/logout', to: 'users#destroy'

  # tickets routes 
  get '/tickets/cheapest', to: 'tickets#cheapest', as: 'cheapest'
  get '/tickets/expensive', to: 'tickets#expensive', as: 'expensive'
  get '/tickets/:id/buy', to: 'tickets#edit', as: 'buy_ticket'
  get '/expensive_tickets', to: 'tickets#expensive_tickets', as: 'expensive_tickets'
  #flights 
  get '/airlines/:airline_id/flights/cheapest', to: 'flights#cheapest', as: 'cheapest_flight'
  get '/airlines/:airline_id/flights/expensive', to: 'flights#expensive', as: 'expensive_flight'

  resources :airlines, only: [:index, :show] do 
   resources :flights, only: [:index, :show]
end
resources :flights, only: [:show] do 
  resources :tickets, only: [:index, :new, :create, :show]
end

resources :flights, only: [:index, :show] 
resources :tickets, only: [:index, :show, :new, :create, :update, :destroy]

resources :passengers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airlines</title>
     <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>  
      <nav> 
        <ul> 
          <li><%= link_to 'Home', root_path %> <br></li>
          <li><%= link_to 'Passenger', passengers_path %></li>
          <li><%= link_to 'Tickets', tickets_path %></li>
          <li><%= link_to 'Flights', "/airlines/#{air_flights}/flights" %></li>
          <li>
        <% if logged_in? %>
          <%= link_to "Logout (#{current_user.username}?)", logout_path %>
          <% else %>
            <%= link_to "Signup", signup_path %>
        <% end %>
          </li>
        </ul>
      </nav>
    <main>
    
    <%= yield %>
    </main>
    <footer>
      <small>&copy; 2020 <strong>Airlines</strong> by Kizito Njoku</small>
    </footer>
  </body>
</html>